/** ###################################################################
**     THIS BEAN MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.

** ###################################################################*/


#ifndef __IQmath_H
#define __IQmath_H

#ifdef __cplusplus
extern "C" {
#endif
/************************************************/

 //#include "IQmathCPP.h"
#include "IQmathLib.h"


/************************************************/
#ifdef __cplusplus
}
#endif

#endif 
